## This set of functions calculates the inverse of matrix (cacheSolve) and stores
## the result in the cache (makeCacheMatrix). If the inverse has already been 
## calculated the result will be returned from the cache, rather than repeating 
## the calculation, as long as the original matrix remains unchanged. Updating
## the matrix will result in the inverse being recalculated and stored in the 
## cache once again. 



##takes a matrix as input and returns a list of functions. Does not actually 
##calculate anything. The makeCacheMatrix is more of a bookkeeper, it holds the 
##matrix and a list of functions which can be executed. The functions themselves
##are not actually executed until called, using subsetting, in cacheSolve
makeCacheMatrix <- function(x = matrix()) {
        i <- NULL       #i is a list which holds the inverse of the matrix, 
                        #it is NULL until the inverse has been calculated 
                        #and passed back    
      
        getInv <- function(){
                i       #returns the value of i, whether i = NULL or i = the
        }               #matrix inverse
      
        get <- function(){
                x       #returns the original matrix so the inverse can be
        }               #calculated. 
       
        setInv <- function(Inverse){
                i <<- Inverse   #assigns the calculated value of the inverse to
        }                       #i and stores the value in the cache 
       
        set <- function(y){
                x <<- y         #overwrites the stored matrix (x) with a new 
                                ##matrix (y) in the cache 
                                
                i <<- NULL      #as the inverse has not been calculated for this
                                #new matrix, i is set once again to NULL
        }
       
        list(getInv = getInv, get = get, setInv = setInv, set = set)       
        #returns a list, with the $getInv subset of the list being equal to the 
        #function assigned to getInv, the $get subset of list being equal to the 
        #function assigned to get, etc.
}


## cacheSolve takes the list generated by makeCacheMatrix as input and 
cacheSolve <- function(x, ...) {
        i <- x$getInv()         #run the getInv function defined in 
                                #makeCacheMatrix and return i 
        
        if(!is.null(i)){        #if the inverse has already been calculated 
                                #it will be stored in the cache and will not
                                #have a value of NULL
                
                message("getting cached data") 
                return(i)       #return the stored inverse from the cache
        }
        data <- x$get() #else call the original matrix
        
        i <- solve(data) #solve the matrix for the inverse
        
        x$setInv(i)     #pass the inverse back to the makeCacheMatrix function
                        #and store this value in the cache
        
        i               #print the matrix inverse to the screen
}
